name ="AYUSH"
age =19
city ="GANDHINAGAR"
print=(name,age,city)

age = 18
age = 19
print(age)
#answer = 19


student_name = "Rahul"
student_age = 18

student_age = 19

print(student_name,student_age)

#answer - the student_age will update to 19 

a, b, c = 10, 20, 30
print(a,b,c)

#answer - due to this sequence every alpabets get their values respectively 


x = y = z = 100
print(x,y,z)

#answer - x , y,z have same values due to assign sign '='


your_name="ayush"
your_age =18
your_city ="lucknow "

print(your_name,your_age,your_city)


student_name ="ayush"
student_roll_no = 202649
student_branch ="B.Tech"
print(student_name,student_roll_no,student_branch)


name = "Rahul"
age =18
city= "Patna"
print(name,age,city)


x=7
y=8
z=9
print(x,y,z)

your_name="ayush"
your_age=18
your_city="lucknow"
print(your_name,your_age,your_city)


 